import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const larken = localFont({
  src: [
    {
      path: "../../public/fonts/larken-variable.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-larken",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${larken.variable} antialiased`}>{children}</body>
    </html>
  );
}
